### PR TITLE
test usage

### PR DESCRIPTION
**Pull request by jarvis-test**

### CODE REVIEW

**Comment by artem-panchenko** [comment]
jarvis works here. you can trigger jarvis-jenkins jobs by comments at the pr.
here, you can find couple examples: [datarobot/usage.md](https://github.com/datarobot/jenkins-jobs/blob/master/jarvis/datarobot/usage.md).
all [jarvis phrases](https://github.com/datarobot/jenkins-jobs/blob/master/jarvis/datarobot/prtests_suite.py).

**Comment by artem-panchenko** [comment]
jarvis please help

**Comment by artem-panchenko** [comment]
Jarvis works here. You can trigger Jarvis-Jenkins jobs by comments at the PR.
Here, you can find couple examples: [DataRobot/Usage.md](https://github.com/datarobot/jenkins-jobs/blob/master/jarvis/DataRobot/Usage.md).
All [jarvis phrases](https://github.com/datarobot/jenkins-jobs/blob/master/jarvis/DataRobot/prtests_suite.py).

**Comment by artem-panchenko** [comment]
jarvis test this

**Comment by artem-panchenko** [comment]
jarvis please help

**Comment by artem-panchenko** [comment]
jarvis please test this

**Comment by artem-panchenko** [comment]
jarvis please test this

**Comment by artem-panchenko** [comment]
jarvis please help

**Comment by artem-panchenko** [comment]
jarvis please test

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestPushEvent(repo=jarvis-test/jarvis-test, pull_id=4, committer=artem-panchenko):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 222, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 325, in push_cancels_queued_builds
    build.cancel()
  File "/usr/local/lib/jarvis/jarvis/api/build.py", line 198, in cancel
    if self._arbiter.get_jenkins(self.master).cancel(self):
  File "/usr/local/lib/jarvis/jarvis/outgoing/jenkins.py", line 95, in cancel
    self.cancel_queue(build.queue_id)
  File "/usr/local/lib/python2.7/site-packages/jenkins/__init__.py", line 521, in cancel_queue
    headers={'Referer': self.server}))
  File "/usr/local/lib/python2.7/site-packages/jenkins/__init__.py", line 430, in jenkins_open
    self.maybe_add_crumb(req)
  File "/usr/local/lib/python2.7/site-packages/jenkins/__init__.py", line 303, in maybe_add_crumb
    self._build_url(CRUMB_URL)), add_crumb=False)
  File "/usr/local/lib/python2.7/site-packages/jenkins/__init__.py", line 448, in jenkins_open
    e.code, e.msg)
JenkinsException: Error in request. Possibly authentication failed [403]: Forbidden

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestPushEvent(repo=jarvis-test/jarvis-test, pull_id=4, committer=artem-panchenko):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 222, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 58, in on_pull_request_update
    build = self.run_test1()
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 21, in run_test1
    context='jarvis-test1')
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 455, in create_build
    url=build.get_job_url())
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 131, in set_status_pending
    self._arbiter.github.set_context(self.repo, sha, context, 'pending', message, url)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 29, in _handle
    result = func(*args, **kwargs)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 195, in set_context
    raise requests.HTTPError(response=response)
HTTPError

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=4, commenter=artem-panchenko, comment="jarvis please run tests

"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 222, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 184, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 38, in run_tests
    build1 = self.run_test1()
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 21, in run_test1
    context='jarvis-test1')
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 455, in create_build
    url=build.get_job_url())
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 131, in set_status_pending
    self._arbiter.github.set_context(self.repo, sha, context, 'pending', message, url)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 29, in _handle
    result = func(*args, **kwargs)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 195, in set_context
    raise requests.HTTPError(response=response)
HTTPError

**Comment by artem-panchenko** [comment]
jarvis please run tests

**Comment by artem-panchenko** [comment]
jarvis please run tests

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=4, commenter=artem-panchenko, comment="jarvis please run tests"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 222, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 184, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 38, in run_tests
    build1 = self.run_test1()
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 21, in run_test1
    context='jarvis-test1')
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 455, in create_build
    url=build.get_job_url())
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 131, in set_status_pending
    self._arbiter.github.set_context(self.repo, sha, context, 'pending', message, url)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 29, in _handle
    result = func(*args, **kwargs)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 202, in set_context
    params)
  File "/usr/local/lib/python2.7/bdb.py", line 55, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/usr/local/lib/python2.7/bdb.py", line 97, in dispatch_exception
    if self.quitting: raise BdbQuit
BdbQuit

**Comment by artem-panchenko** [comment]
jarvis please run tests

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=4, commenter=artem-panchenko, comment="jarvis please run tests"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 222, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 184, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 38, in run_tests
    build1 = self.run_test1()
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 21, in run_test1
    context='jarvis-test1')
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 455, in create_build
    url=build.get_job_url())
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 131, in set_status_pending
    self._arbiter.github.set_context(self.repo, sha, context, 'pending', message, url)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 29, in _handle
    result = func(*args, **kwargs)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 204, in set_context
    params)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 144, in post
    return self._request_and_validate(requests.post, url, params, throw)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 62, in wrapper
    raise e
HTTPError

**Comment by artem-panchenko** [comment]
jarvis please run tests

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=4, commenter=artem-panchenko, comment="jarvis please run tests"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 222, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 184, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 38, in run_tests
    build1 = self.run_test1()
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 21, in run_test1
    context='jarvis-test1')
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 455, in create_build
    url=build.get_job_url())
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 131, in set_status_pending
    self._arbiter.github.set_context(self.repo, sha, context, 'pending', message, url)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 29, in _handle
    result = func(*args, **kwargs)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 206, in set_context
    params)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 146, in post
    return self._request_and_validate(requests.post, url, params, throw)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 57, in wrapper
    result = func(*args, **kwargs)
HTTPError

**Comment by artem-panchenko** [comment]
jarvis please run tests

**Comment by artem-panchenko** [comment]
jarvis please run tests

**Comment by artem-panchenko** [comment]
jarvis please run tests

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=4, commenter=artem-panchenko, comment="jarvis please run tests"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 222, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 184, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 38, in run_tests
    build1 = self.run_test1()
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 21, in run_test1
    context='jarvis-test1')
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 455, in create_build
    url=build.get_job_url())
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 131, in set_status_pending
    self._arbiter.github.set_context(self.repo, sha, context, 'pending', message, url)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 29, in _handle
    result = func(*args, **kwargs)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 205, in set_context
    params)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 145, in post
    return self._request_and_validate(requests.post, url, params, throw)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 59, in wrapper
    retries += 1
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 59, in wrapper
    retries += 1
  File "/usr/local/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/local/lib/python2.7/bdb.py", line 68, in dispatch_line
    if self.quitting: raise BdbQuit
BdbQuit

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=4, commenter=artem-panchenko, comment="jarvis please run tests




"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 222, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 184, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 40, in run_tests
    build2 = self.run_test2()
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 28, in run_test2
    context='jarvis-test2')
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 455, in create_build
    url=build.get_job_url())
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 131, in set_status_pending
    self._arbiter.github.set_context(self.repo, sha, context, 'pending', message, url)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 29, in _handle
    result = func(*args, **kwargs)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 202, in set_context
    params)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 142, in post
    return self._request_and_validate(requests.post, url, params, throw)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 58, in wrapper
    retries += 1
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 58, in wrapper
    retries += 1
  File "/usr/local/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/local/lib/python2.7/bdb.py", line 68, in dispatch_line
    if self.quitting: raise BdbQuit
BdbQuit

**Comment by artem-panchenko** [comment]
jarvis please stop testing

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=4, commenter=artem-panchenko, comment="jarvis please stop testing"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 222, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 184, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 311, in cancel_abort_on_comment
    for build in self.push_cancels_queued_builds():
AttributeError: 'dict' object has no attribute 'context'

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=4, commenter=artem-panchenko, comment="jarvis please stop testing

"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 222, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 184, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 312, in cancel_abort_on_comment
    self.set_status_failure(build.context.context, message='Manually canceled')
AttributeError: 'dict' object has no attribute 'context'

**Comment by jarvis-test** [comment]
jarvis please run tests

**Pull request merged**
