### PR TITLE
Testing no diff PR

### PR DESCRIPTION
**Pull request by artem-panchenko**

### CODE REVIEW

**Comment by jarvis-test** [comment]
jarvis please test this

**Comment by jarvis-test** [comment]
jarvis please test this

**Comment by jarvis-test** [comment]
jarvis please test this

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=6, commenter=jarvis-test, comment="jarvis please test this"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 225, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 186, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/custom-jarvis-suites/jarvis_test_suite.py", line 60, in on_pull_request_update
    if not self.files:
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 605, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'JSuite' object has no attribute 'files'

**Comment by jarvis-test** [comment]
jarvis please test this

**Comment by jarvis-test** [comment]
jarvis please test this

**Comment by artem-panchenko** [comment]
No changes to test

**Pull request closed without merging**
