### PR TITLE
test4

### PR DESCRIPTION
**Pull request by jarvis-test**

### CODE REVIEW

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestNewEvent(repo=jarvis-test/jarvis-test, pull_id=3, author=jarvis-test):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 222, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 748, in on_pull_request_new
    return self.on_pull_request_update()
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 39, in on_pull_request_update
    build.when('success').callback(self.run_test2)
  File "/usr/local/lib/jarvis/jarvis/api/callback.py", line 52, in callback
    target = Callback(func, args, condition=self)
  File "/usr/local/lib/jarvis/jarvis/api/callback.py", line 17, in __init__
    self.method_self = six.get_method_self(func)
AttributeError: 'bool' object has no attribute 'im_self'

**Comment by jarvis-test** [comment]
jarvis please test this

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=3, commenter=jarvis-test, comment="jarvis please test this
"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 222, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 182, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 40, in on_pull_request_update
    build.when('success').callback(self.run_test2)
  File "/usr/local/lib/jarvis/jarvis/api/callback.py", line 52, in callback
    target = Callback(func, args, condition=self)
  File "/usr/local/lib/jarvis/jarvis/api/callback.py", line 17, in __init__
    self.method_self = six.get_method_self(func)
AttributeError: 'bool' object has no attribute 'im_self'

**Comment by jarvis-test** [comment]
jarvis test 2

**Comment by jarvis-test** [comment]
jarvis please test 2

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=3, commenter=jarvis-test, comment="jarvis run tests"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 224, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 184, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 38, in run_tests
    build1 = run_test1()
NameError: global name 'run_test1' is not defined

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=3, commenter=jarvis-test, comment="jarvis run tests

"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 224, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 184, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 40, in run_tests
    build2 = self.run_tests2()
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 534, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'JSuite' object has no attribute 'run_tests2'

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by jarvis-test** [comment]
jarvis run tests

**Comment by jarvis-test** [comment]
jarvis run tests

**Pull request closed without merging**
