### PR TITLE
test2

### PR DESCRIPTION
**Pull request by jarvis-test**
jarvis:test_option = 12

### CODE REVIEW

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestNewEvent(repo=jarvis-test/jarvis-test, pull_id=2, author=jarvis-test):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 222, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 748, in on_pull_request_new
    return self.on_pull_request_update()
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 19, in on_pull_request_update
    return self.run_test()
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 13, in run_test
    context='jarvis-test')
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 449, in create_build
    url=build.get_job_url())
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 130, in set_status_pending
    self._arbiter.github.set_context(self.repo, sha, context, 'pending', message, url)
  File "/usr/local/lib/jarvis/jarvis/outgoing/github.py", line 40, in _handle
    raise_from(GithubProbablyPermissionDenied(), e)
  File "/usr/local/lib/python2.7/site-packages/future/utils/__init__.py", line 454, in raise_from
    raise e
GithubProbablyPermissionDenied

**Comment by artem-panchenko** [comment]
GitHub user 'artem-panchenko' used in Jarvis doesn't have enough permissions to handle events from this repository!

**Comment by jarvis-test** [comment]
jarvis please launch mbtest custom

**Comment by jarvis-test** [comment]
jarvis launch mbtest custom

**Comment by jarvis-test** [comment]
jarvis launch mbtest custom

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=2, commenter=jarvis-test, comment="jarvis launch mbtest custom
x"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 221, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 182, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/jarvis/api/utils.py", line 109, in extend
    items = flatten(items)
  File "/usr/local/lib/jarvis/jarvis/api/utils.py", line 66, in flatten
    for item in items:
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 38, in launch_mbtest
    if self.built_bases_versions:
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 529, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'JSuite' object has no attribute 'built_bases_versions'

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=2, commenter=jarvis-test, comment="jarvis launch mbtest custom"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 221, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 182, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/jarvis/api/utils.py", line 109, in extend
    items = flatten(items)
  File "/usr/local/lib/jarvis/jarvis/api/utils.py", line 66, in flatten
    for item in items:
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 54, in launch_mbtest
    mbtest_build = self.create_build(job_name, params, master='shrink')
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 449, in create_build
    url=build.get_job_url())
  File "/usr/local/lib/jarvis/jarvis/api/build.py", line 193, in get_job_url
    self._get_jenkins().get_job_url(self.job)
  File "/usr/local/lib/jarvis/jarvis/api/build.py", line 190, in _get_jenkins
    return self._arbiter.get_jenkins(self.master)
  File "/usr/local/lib/jarvis/jarvis/service/arbiter.py", line 89, in get_jenkins
    raise ValueError('No such jenkins configuration: '+name)
ValueError: No such jenkins configuration: shrink

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=2, commenter=jarvis-test, comment="jarvis launch mbtest custom"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 255, in do_handle
    suite.cleanup()
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 323, in cleanup
    self._arbiter.cleanup(self)
  File "/usr/local/lib/jarvis/jarvis/service/arbiter.py", line 308, in cleanup
    cb_model = Callback.from_api(session, callback)
  File "/usr/local/lib/jarvis/jarvis/models/suite.py", line 94, in from_api
    condition=Condition.from_api(session, callback.condition),
  File "/usr/local/lib/jarvis/jarvis/models/suite.py", line 156, in from_api
    build_dep_id = condition.target._model.id
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=2, commenter=jarvis-test, comment="jarvis launch mbtest custom
x"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 221, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 182, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/jarvis/api/utils.py", line 109, in extend
    items = flatten(items)
  File "/usr/local/lib/jarvis/jarvis/api/utils.py", line 66, in flatten
    for item in items:
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 56, in launch_mbtest
    self.pull_comment(textwrap.dedent("Please follow this link, specify parameters for custom MBTests and click"
NameError: global name 'textwrap' is not defined

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': None/input/

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': None/input/

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=2, commenter=jarvis-test, comment="jarvis launch mbtest custom
x"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 221, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 182, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/jarvis/api/utils.py", line 109, in extend
    items = flatten(items)
  File "/usr/local/lib/jarvis/jarvis/api/utils.py", line 66, in flatten
    for item in items:
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 59, in launch_mbtest
    lambda: self.pull_comment(textwrap.dedent("Please follow this link, specify parameters "
  File "/usr/local/lib/jarvis/jarvis/api/callback.py", line 52, in callback
    target = Callback(func, args, condition=self)
  File "/usr/local/lib/jarvis/jarvis/api/callback.py", line 17, in __init__
    self.method_self = six.get_method_self(func)
AttributeError: 'function' object has no attribute 'im_self'

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=2, commenter=jarvis-test, comment="jarvis launch mbtest custom
"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 221, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 182, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/jarvis/api/utils.py", line 109, in extend
    items = flatten(items)
  File "/usr/local/lib/jarvis/jarvis/api/utils.py", line 66, in flatten
    for item in items:
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 63, in launch_mbtest
    mbtest_build.when('started').callback(self._comment_with_mbtest_link())
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 529, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'JSuite' object has no attribute '_comment_with_mbtest_link'

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=2, commenter=jarvis-test, comment="jarvis launch mbtest custom
x"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 255, in do_handle
    suite.cleanup()
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 323, in cleanup
    self._arbiter.cleanup(self)
  File "/usr/local/lib/jarvis/jarvis/service/arbiter.py", line 308, in cleanup
    cb_model = Callback.from_api(session, callback)
  File "/usr/local/lib/jarvis/jarvis/models/suite.py", line 93, in from_api
    arguments=json_attrs.dumps(callback.args),
  File "/usr/local/lib/jarvis/jarvis/service/json_attrs.py", line 67, in dumps
    return json.dumps(obj, cls=JSONAttrsEncoder)
  File "/usr/local/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/jarvis/jarvis/service/json_attrs.py", line 33, in default
    return json.JSONEncoder.default(self, model)
  File "/usr/local/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: JarvisBuild(job=mbtest_launch_pipeline, build_id=None, queue_id=None) is not JSON serializable

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': http://172.17.0.1:8080/job/mbtest_launch_pipeline/12//input/

**Comment by jarvis-test** [comment]
jarvis please launch mbtest

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=2, commenter=jarvis-test, comment="jarvis please launch mbtest"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 221, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 182, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 30, in launch_mbtest
    parametrized = 'custom' in custom
TypeError: argument of type 'NoneType' is not iterable

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=2, commenter=jarvis-test, comment="jarvis please launch mbtest custom"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 221, in do_handle
    builds.extend(handler())
  File "/usr/local/lib/jarvis/jarvis/api/suite/sugar.py", line 182, in invoke_phrase_targets
    builds += method(**match_dict)
  File "/usr/local/lib/jarvis/suites/jarvis_test_suite.py", line 56, in launch_mbtest
    mbtest_build = self.create_build(job_name, params, master='shrink')
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 449, in create_build
    url=build.get_job_url())
  File "/usr/local/lib/jarvis/jarvis/api/build.py", line 193, in get_job_url
    self._get_jenkins().get_job_url(self.job)
  File "/usr/local/lib/jarvis/jarvis/api/build.py", line 190, in _get_jenkins
    return self._arbiter.get_jenkins(self.master)
  File "/usr/local/lib/jarvis/jarvis/service/arbiter.py", line 89, in get_jenkins
    raise ValueError('No such jenkins configuration: '+name)
ValueError: No such jenkins configuration: shrink

**Comment by artem-panchenko** [comment]
Unexpected failure caught while JSuite was handling PullRequestCommentEvent(repo=jarvis-test/jarvis-test, pull_id=2, commenter=jarvis-test, comment="jarvis please launch mbtest custom"):
Traceback (most recent call last):
  File "/usr/local/lib/jarvis/jarvis/service/handlers.py", line 255, in do_handle
    suite.cleanup()
  File "/usr/local/lib/jarvis/jarvis/api/suite/jarvis_suite.py", line 323, in cleanup
    self._arbiter.cleanup(self)
  File "/usr/local/lib/jarvis/jarvis/service/arbiter.py", line 308, in cleanup
    cb_model = Callback.from_api(session, callback)
  File "/usr/local/lib/jarvis/jarvis/models/suite.py", line 94, in from_api
    condition=Condition.from_api(session, callback.condition),
  File "/usr/local/lib/jarvis/jarvis/models/suite.py", line 156, in from_api
    build_dep_id = condition.target._model.id
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': http://172.17.0.1:8080/job/mbtest_launch_pipeline/31//input/

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': http://172.17.0.1:8080/job/mbtest_launch_pipeline/32//input/

**Comment by jarvis-test** [comment]
jarvis launch mbtest custom

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': http://172.17.0.1:8080/job/mbtest_launch_pipeline/34//input/

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': http://172.17.0.1:8080/job/mbtest_launch_pipeline/35//input/

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': http://172.17.0.1:8080/job/mbtest_launch_pipeline/36//input/

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': http://172.17.0.1:8080/job/mbtest_launch_pipeline/37//input/

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': http://172.17.0.1:8080/job/mbtest_launch_pipeline/38//input/

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': http://172.17.0.1:8080/job/mbtest_launch_pipeline/39//input/

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': http://172.17.0.1:8080/job/mbtest_launch_pipeline/40//input/

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': http://172.17.0.1:8080/job/mbtest_launch_pipeline/41//input/

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': http://172.17.0.1:8080/job/mbtest_launch_pipeline/42//input/

**Comment by jarvis-test** [comment]
jarvis please launch mbtest custom

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': http://172.17.0.1:8080/job/mbtest_launch_pipeline/43//input/

**Comment by artem-panchenko** [comment]
Please follow this link, specify parameters for custom MBTests and click 'Proceed': http://172.17.0.1:8080/job/mbtest_launch_pipeline/46//input/

**Comment by jarvis-test** [comment]
jarvis please test this out

**Comment by artem-panchenko** [comment]
jarvis please help

**Comment by artem-panchenko** [comment]
Jarvis works here. You can trigger Jarvis-Jenkins jobs by comments at the PR.
Here, you can find couple examples: [DataRobot/Usage.md](https://github.com/datarobot/jenkins-jobs/blob/master/jarvis/DataRobot/Usage.md).
All [jarvis phrases](https://github.com/datarobot/jenkins-jobs/blob/master/jarvis/DataRobot/prtests_suite.py).

**Comment by artem-panchenko** [comment]
jarvis please help

**Comment by artem-panchenko** [comment]
Jarvis works here. You can trigger Jarvis-Jenkins jobs by comments at the PR.
Here, you can find couple examples: [DataRobot/Usage.md](https://github.com/datarobot/jenkins-jobs/blob/master/jarvis/DataRobot/Usage.md).
All [jarvis phrases](https://github.com/datarobot/jenkins-jobs/blob/master/jarvis/DataRobot/prtests_suite.py).

**Pull request closed without merging**
